import { Header } from "./components/header/Header"
import { Footer } from "./components/footer/Footer"
import {ThemeProvider} from "./app"
import styles from '../app/styles/main.module.scss'
import { useState } from "react"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode
}) {
  
  

  
  return (
    <html lang="en">
                <body className={styles.container}>
         
  
          
         <ThemeProvider>{children}</ThemeProvider>
         
         
         </body>
    </html>
  )
}
